// Generated by CoffeeScript 1.9.3
(function() {
  var Page;

  module.exports = Page = (function() {
    function Page(name, path, parent1, sections, children, important) {
      this.name = name;
      this.path = path;
      this.parent = parent1;
      this.sections = sections;
      this.children = children;
      this.important = important;
      if (this.sections == null) {
        this.sections = [];
      }
      if (this.children == null) {
        this.children = [];
      }
      if (this.important == null) {
        this.important = [];
      }
    }

    Page.prototype.directChild = function(pname) {
      var child, j, len, page, ref;
      ref = this.children;
      for (j = 0, len = ref.length; j < len; j++) {
        child = ref[j];
        if (child.name === pname) {
          page = child;
        }
      }
      if (page == null) {
        console.error('no child for this name exists:');
        console.error(pname);
        process.exit(1);
      }
      return page;
    };

    Page.prototype.recursiveChild = function(pnames) {
      var j, len, pname, tmp;
      tmp = this;
      for (j = 0, len = pnames.length; j < len; j++) {
        pname = pnames[j];
        tmp = tmp.directChild(pname);
      }
      return tmp;
    };

    Page.parsePage = function(page, parent) {
      var c, i, j, k, len, len1, parsedPage, ref, ref1;
      parsedPage = new Page(page.name, page.path, parent, page.sections, [], []);
      if (page.children != null) {
        ref = page.children;
        for (j = 0, len = ref.length; j < len; j++) {
          c = ref[j];
          parsedPage.children.push(Page.parsePage(c, parsedPage));
        }
      }
      if (page.important != null) {
        ref1 = page.important;
        for (k = 0, len1 = ref1.length; k < len1; k++) {
          i = ref1[k];
          parsedPage.important.push(Page.parsePage(i, parsedPage));
        }
      }
      return parsedPage;
    };

    Page.parse = function(ms) {
      var menu;
      menu = Page.parsePage(ms, null);
      return menu;
    };

    return Page;

  })();

}).call(this);
